# Generated by Django 4.0.3 on 2022-04-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_images_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
